title: <center> Bryan Rickens </center>
logo: "/images/logo.png?raw=true" 
description: <center><a href="https://www.linkedin.com/in/bryanrickens/">View My LinkedIn Profile</a></center> <br> A nontraditional student of Data Science at the College of Charleston making the most out of my unique background after having previously worked in the manufacturing industry for many years. <br><br> For more information on my journey, you can read about it <a href="https://today.cofc.edu/2022/11/08/cofc-center-for-academic-performance-and-persistence//">here</a> in an article published by The College Today.
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

